steps:
- name: gcr.io/kaniko-project/executor:v1.9.1
  args:
  - --destination=gcr.io/$PROJECT_ID/${REPO_NAME}/${REPO_NAME}:${COMMIT_SHA}
  - --destination=gcr.io/$PROJECT_ID/${REPO_NAME}/${REPO_NAME}:${BRANCH_NAME}
  - --destination=gcr.io/$PROJECT_ID/${REPO_NAME}/${REPO_NAME}:${TAG_NAME}
  - --cache=true
  - --cache-ttl=6h
