package com.supr.orderservice.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorEnum {
  SOMETHING_WENT_WRONG("ERR_ORDER_0", "Something went wrong!"),
  USER_FRIENDLY_SOMETHING_WENT_WRONG("ERR_ORDER_1",
      "Sorry! It's not you, it is us. We request you to please try again"),
  ORDER_NOT_FOUND_FOR_STORE("ERR_ORDER_0011", "Order not found for the store "),
  ORDER_NOT_FOUND_FOR_STORE_FOR_SELECTED_PERIOD("ERR_ORDER_002",
      "Order not found for the store for the selected period"),
  ORDER_NOT_FOUND_FOR_SELECTED_PERIOD("ERR_ORDER_003", "Order not found for the selected period"),
  ORDER_ITEMS_NOT_FOUND("ERR_ORDER_004", "No order item found for the shared IDs"),
  MERCHANT_INVOICE_NOT_FOUND("ERR_MI-001", "No Invoice available for this store"),
  ORDERS_NOT_FOUND_FOR_GENERATING_INVOICE("ERR_MI-002",
      "No Orders available for generating invoice in given period for this store OR " +
          "Invoice already generated. Please check invoice view"),
  STORE_NOT_FOUND("ERR_MI-003", "Store details not found to generate invoice"),
  NO_CARD_DETAILS_AVAILABLE("ERR_ORDER_4", "No card details available"),
  INVALID_CARD_EXPIRY("ERR_ORDER_5", "Please enter a valid expiry date"),
  INVALID_CARD_NUMBER("ERR_ORDER_6", "Please enter a valid card number"),
  PAYMENT_FAILED_FOR_CUSTOMER("ERR_ORDER_7",
      "We were unable to process your payment. Please try using another card or check your CVV."),
  NOT_ALLOWED_TO_SAVE_MORE_THAN_5_CARDS("ERR_ORDER_8", "Sorry, you cannot save more than 5 cards"),
  REFUND_ALREADY_DONE("ERR_ORDER_9", "Sorry, refund for this order is already done. Please connect with customer care"),
  NO_USER_FOUND_WITH_THE_GIVEN_IDENTITY("ERR_ORDER_10", "No user found with given identity"),
  ERROR_WHILE_UPLOADING_TO_GCP("ERR_ORDER_11", "Error while uploading the file to GCP.."),
  ORDER_ITEM_NOT_FOUND("ERR_ORDER_12", "No order item found for the shared ID"),
  ORDER_NOT_FOUND("ERR_ORDER_13", "No Order details found with the given order id"),
  NULL_STATUS_RESPONSE_FROM_BRIDGE("ERR_ORDER_14", "Got null status (or) response from bridge for order"),
  ORDER_NOT_IN_DELIVERED("ERR_ORDER_15", "Order is not in delivered State"),
  ERROR_WHILE_GENERATING_CSV("ERR_ORDER_16", "Error while generating csv.."),
  INVOICE_FOR_DELIVERED_STATE_ONLY("ERR_ORDER_17", "Invoice can be generated only in delivered state.."),
  TRANSACTION_FAILED("ERR_ORDER_18", "Transaction failed"),
  QUANTITY_LESS_THAN_OR_EQUAL_TO_ZERO("ERR_ORDER_19", "Quantity should be greater than ZERO"),
  ERROR_IN_DATE_PARSING_FOR_STORE_REPORT_GENERATION("ERR_ORDER_20",
      "Error in parsing the date for store report generation."),
  FAILED_TO_UPDATE_INVOICE_NUMBER_FOR_ORDERS("ERR_ORDER_21", "Unable to update invoice number against orders"),
  PICKER_MAPPING_FAILED("ERR_ORDER_22", "Picker mapping failed for the shared order"),
  STORE_ATTRIBUTE_UPDATE_FAILED("ERR_ORDER_23", "Store attribute update failed"),
  PICKER_ALREADY_MAPPED("ERR_ORDER_24", "Picker is already mapped for the shared order"),
  INCORRECT_QUANTITY_OR_REFUND_AMOUNT("ERR_ORDER_25",
      "Either Quantity or Refund Amount entered is not correct for the items"),
  QUANTITY_CHANGE_NOT_IN_RANGE("ERR_ORDER_26", "Quantity passed is not in the allowed range to approve order"),
  NO_TRANSITION_FOUND("ERR_ORDER_27", "No transition from the current state"),
  CANCELLED_ITEMS_IN_APPROVE_REQUEST("ERR_ORDER_28", "Request failed due to presence of cancelled items"),
  LOGISTICS_ERROR("ERR_ORDER_29",
      "Unable to process order due to Logistics, please contact Merchant Support."),
  PAYMENT_FAILED_FOR_MERCHANT("ERR_ORDER_30",
      "Unable to process payment, please contact Merchant Support."),
  NO_STORES_FOUND_FOR_MERCHANT_ID("ERR_ORDER_31", "No Stores found for the shared merchant Ids"),
  NO_STORES_AVAILABLE_FOR_MERCHANT("ERR_ORDER_32", "No stores found for the shared merchant ID"),
  SIMILAR_REQUEST_IN_PROGRESS("ERR_ORDER_33", "Similar request in progress"),
  ORDER_APPROVAL_IN_PROGRESS("ERR_ORDER_34", "Order approval in progress. Please try after sometime"),
  MISMATCH_IN_CURRENT_APPROVAL_REQUEST("ERR_ORDER_35",
      "Current request is not matching with the previously made request"),
  MISMATCH_IN_CAPTURED_AMOUNT("ERR_ORDER_36", "Mismatch in captured amount v/s order price"),
  MISMATCH_IN_REFUND_AMOUNT("ERR_ORDER_37", "Mismatch in refund amount v/s order price"),
  MISMATCH_IN_REVERSE_AMOUNT("ERR_ORDER_38", "Mismatch in reverse amount v/s order price"),
  ORDER_ALREADY_PROCESSED_BY_MERCHANT("ERR_ORDER39", "Order is already processed by merchant"),
  APPROVAL_REQUEST_IN_PROGRESS_BY_MERCHANT("ERR_ORDER_40", "Approval request in progress by merchant"),
  ORDER_ALREADY_PROCESSED_BY_MERCHANT_FOR_REPLACEMENT("ERR_ORDER41",
      "Order is already processed by merchant for replacement"),
  INVALID_REQUEST("ERR_ORDER_41", "Invalid request"),
  ORDER_IN_PROGRESS("ERR_ORDER_42", "Your current order is being processed. " +
      "You will be able to update your payment method once the order is shipped."),
  NO_ACTIVE_SUBSCRIPTION("ERR_ORDER_43", "Oh no! Looks like there is no active subscription."),
  INVALID_PAYMENT_MODE("ERR_ORDER_44", "Invalid payment mode selected"),
  INVALID_ORDER_ID("ERR_ORDER_45", "Invalid order id"),
  NO_SUCH_NOTIFICATION_FOUND_FOR_THE_STORE("ERR_ORDER_46", "No such notification found for the store"),
  ANOTHER_SUBSCRIPTION_IN_PROGRESS("ERR_ORDER_47", "Another subscription request is already in progress"),
  NEW_SUBSCRIPTION_NOT_ALLOWED_FROM_PAGE("ERR_ORDER_48",
      "Please go to the Orders tab to update your payment method for current in flight order(s)"),
  PAYMENT_AUTHORIZATION_FAILED("ERR_ORDER_49", "Order Authorization failed to confirm order"),
  MORE_NUMBER_OF_REPLACEMENTS("ERR_ORDER_50", "More than 9 replacement items are selected"),
  ORDER_IS_BEING_PROCESSED("ERR_ORDER_51", "Order is being processed"),
  PAYMENT_FAILURE_ORDER_SUBSCRIPTION("ERR_ORDER_52", "Payment failed!! Please try again after sometime!!"),
  NOON_AUTH_CLIENT_ERROR("ERR_ORDER_52", "Error while calling Noon auth API"),
  NOON_SHIPMENT_CLIENT_ERROR("ERR_ORDER_53", "Error while calling Noon shipment API"),
  NOON_INVOICE_CLIENT_ERROR("ERR_ORDER_54", "Error while calling Noon invoice API"),
  APPLE_PAY_DOWN_ERROR_MESSAGE("ERR_ORDER_55", "Apple pay is down temporarily. Please try another payment method"),
  MORE_THAN_ONE_BAR_CODE_NOT_ALLOWED_FOR_WEIGHTED_ITEM("ERR_ORDER_56",
      "More than one bar code is not allowed for weighted item"),
  NO_OF_BAR_CODES_NOT_MATCHING_QUANTITY_FOR_NON_WEIGHTED_ITEM("ERR_ORDER_57",
      "No of bar-codes does not match with the quantity for non weighted item"),
  BAR_CODES_SHOULD_BE_PRESENT_FOR_SCAN_TYPE_BAR_CODE("ERR_ORDER_58", "Barcode list empty for scan-type as barcode"),
  INVALID_SCAN_TYPE_FOR_STORE_ATTRIBUTE_ADD_UPDATE("ERR_ORDER_59", "Invalid value for scan type"),
  CREATE_NOON_SHIPMENT_FOR_INVALID_ORDER_STATE("ERR_ORDER_60",
      "Invalid order state for create shipment call for dark store"),
  REQUEST_QUANTITY_MISMATCH_IN_SCAN("ERR_ORDER_61", "Mismatch in request quantity while scanning"),
  CANCELLATION_NOT_ALLOWED_POST_ORDER_APPROVAL("ERR_ORDER_62",
      "Oops! Your order has been confirmed and packed by the merchant and cannot be cancelled now"),
  BARCODE_CANNOT_BE_BLANK("ERR_ORDER_63", "Entered barcode should not be empty"),
  QUANTITY_CANNOT_BE_NULL_FOR_BARCODE("ERR_ORDER_64", "Quantity associated with barcode cannot be null"),
  ALREADY_SUBSCRIBED_FOR_PASS("ERR_ORDER_65", "Delivery pass is already active for your account!!"),
  SUBSCRIPTION_IS_DISABLED("ERR_ORDER_66", "Chosen subscription is disabled!!"),
  RETURN_ACCEPTANCE_QTY_GREATER_THAN_ORDER_ITEM_QTY("ERR_ORDER_67",
      "Return acceptance quantity cannot be greater than order item quantity"),
  INVOICE_ALREADY_GENERATED_FOR_ORDER("ERR_ORDER_68", "Invoice is already generated for this order"),
  ORDER_ITEM_NOT_IN_PROGRESS_STATE_FOR_ADMIN_APPROVAL("ERR_ORDER_69", "OrderItem is not in valid state to be approved"),
  RETURN_UPDATABLE_QTY_GREATER_THAN_ORDER_ITEM_QTY("ERR_ORDER_70",
      "Return updatable quantity cannot be greater than order item quantity"),
  DELIVERY_COMPLETE_FROM_STORE_PORTAL_FOR_SHIPPED_ORDERS_ONLY("ERR_ORDER_71",
      "Order can be delivery complete only from SHIPPED status"),
  DELIVERY_COMPLETE_FROM_STORE_PORTAL_FOR_DROPSHIP_ORDERS_ONLY("ERR_ORDER_72",
      "Order can be delivery complete only from SHIPPED status"),
  ACCOUNT_LINE_ITEMS_NOT_FOUND_FOR_SELECTED_PERIOD("ERR_ORDER_73", "Account Line Items not " +
      "found for the selected period"),
  ALL_SLOTS_FULL_MESSAGE("ERR_ORDER_74", "All slots are full"),
  NO_FUTURE_ORDERS_FOUND("ERR_ORDER_75", "Future orders not found:"),
  SAME_SLOT_RESCHEDULE("ERR_ORDER_76", "can not reschedule to the same slot"),
  PLACE_SLOTTED_TYPE_ORDER("ERR_ORDER_77", "please place/reschedule only SLOTTED orders"),
  SLOT_NULL("ERR_ORDER_78", "slot can not be null for slotted order");

  private final String errorCode;
  private final String errorMessage;
}
