package com.supr.orderservice.enums;

public enum NextAction {
  PLACE_ORDER,
  SUBSCRIPTION_CAPTURE,
  SUBSCRIPTION_REFUND,
  AUTHORIZE_PAYMENT_FOR_USER_ORDER,
  RETRY_AUTHORIZE_PAYMENT_FOR_USER_ORDER,
  CAPTURE_PAYMENT_FOR_USER_ORDER,
  SUBSCRIPTION_FAILED_USER_ORDER,
  CREATE_SHIPMENT,
  CANCEL_USER_ORDER,
  SCHEDULE_CANCEL_USER_ORDER
}
