package com.supr.orderservice.enums;

public enum NotificationEventEnum {
    ORDER_CONFIRMED,
    ORDER_PICKED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    ORDER_CANCELLED_BY_CUSTOMER,
    ITEM_CANCELLED,
    ITEMS_CANCELLED,
    ORDER_MODIFIED,
    CANCELLED_BY_LOGISTICS,
    ORDER_PENDING_APPROVAL,
    CHANGE_PAYMENT,
    PAYMENT_FAILED,
}
