package com.supr.orderservice.enums;

public enum OrderChangeEvent {
    SENDER_ORDER_CHECKOUT,
    SENDER_PLACE_ORDER,
    RECEIVER_CLICKED_GIFT,
    RECEIVER_RECEIVED_GIFT,
    RECEIVER_OPEN_GIFT,
    RECEIVER_ACCEPTED_GIFT,
    RECEIVER_SWAPPED_GIFT,
    GIFT_SWAPPED_LOWER,
    SENDER_CANCEL_ORDER,
    SENDER_ORDER_SCHEDULED,
    PROCESS_ORDER_SCHEDULED,
    SENDER_PAYMENT_FAILED,
    SENDER_PAYMENT_SUCCESS,
    RECEIVER_PAYMENT_FAILED,
    RECEIVER_PAYMENT_SUCCESS,
    CANCELLED_BY_SELLER,
    RECEIVER_GIFT_EXPIRED,
    GIFT_UNDELIVERED,
    GIFT_PARTIALLY_DELIVERED,
    GIFT_DELIVERED,
    GIFT_SHIPPED,
    SENDER_GIFT_SCHEDULED,
    CANCELLED_BY_LOGISTICS

}
